### ISSUE TITLE
Good website LOTS of lag

### ISSUE THREAD

**Issue by DeusOmmuim** [D3ch/hell#1]
Real good website Little laggy Prob just remove the background and it will be fixed Im putting it in my Unblocked games Repo

**Comment by FoxMoss** [comment]
Learn How to Properly Capitalize sentences

**Comment by UnClausus-Ludi** [comment]
### why be a asshole

**Comment by UnClausus-Ludi** [comment]
?

**Comment by UnClausus-Ludi** [comment]
*Learn how to properly 
capitalise sentences.

**Comment by FoxMoss** [comment]
> ### why be a asshole

i thought it was a little funny
