### ISSUE TITLE
ripped 3kh0 games

### ISSUE THREAD

**Issue by fowntain** [D3ch/hell#2]
did you even ask 3kh0's permission to just completely rip his hard work of compiling all of those games? at least give credit if nothing else

**Comment by D3ch** [comment]
check credits in the readme

**Comment by 3kh0** [comment]
lol

**Comment by diamondbroplayz** [comment]
> did you even ask

buddy, are there any game sites that dont do it? also let me quote the repo.

> As for this repo, it has been archived for preservation and storage. You are free to use these games however you see fit. If you wish, you can give credit. Thank you.
