### ISSUE TITLE
VidFeed Games Issues?

### ISSUE THREAD

**Issue by DiscretionIsAdvised** [D3ch/hell#7]
Are the VidFeed games supposed to not load properly when you access the video part???

**Comment by D3ch** [comment]
how are you playing vidfeed??? it was removed from games because of that issue.

**Comment by DiscretionIsAdvised** [comment]
I must have an old version lol. Or I ran the code back by accident. What was wrong with the loading? Was it because it was local?

**Comment by D3ch** [comment]
I'm gonna be honest, I have no idea what the problem is.

**Comment by DiscretionIsAdvised** [comment]
I think it's how it's embedded. It can't load the actual game files because the linked videos are streamed from its own server that isn't able to connect to the game. However, I don't think it can be fixed unless you manage to somehow allow the connection, or somehow get the videos themselves downloaded to the game. This is just speculation, and I am no real coder, I just know a lot about computers lol.

**Comment by DiscretionIsAdvised** [comment]
Wait it also could be that the website is open source, and that the VidFeed game is closed source. Therefor, it cannot load properly.
